### ISSUE TITLE
bootstrap dropdown menu not working

### ISSUE THREAD

**Issue by Sri-K** [railstutorial/sample_app_2nd_ed#14]
hi, i am a beginner and doing the rails tutorial twitter app. My bootstrap dropdown menu is not working. When i do the rspec  test, its pass. But the dropdown menu is not working. please help me. thanks in advance

**Comment by niltonvasques** [comment]
Thanks Raduh! I had the same problem too, and only solution was change bootstrap to bootstrap-dropdown.

**Comment by acandael** [comment]
I'm having the same issue. I am using Rails 5.1.2, downgrading to bootstrap-sass 2.0.4.1 and using bootstrap-dropdown didn't fix it for me.

**Comment by mhartl** [comment]
This repo is several years out of date. I've added a note to that effect.

I suggest using the [latest version](http://railstutorial.org/book) of the tutorial. See the [help page](http://railstutorial.org/help) for more information.
